version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=visitor_counter
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
